FROM mcr.microsoft.com/devcontainers/base:${templateOption:imageVariant}

# RUN mkdir -p /opt/devcontainers \
#     && echo "no color" > /usr/local/etc/devcontainers/greeting.txt \
#     # && chown -R vscode:vscode /usr/local/etc/devcontainers/greeting.txt